apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: payments-v1-afterpay-token-api
  title: Payments V1 AfterPay Token API
  namespace: customer
  description: This API gets token from AfterPay
spec:
  type: openapi
  lifecycle: production
  owner: group:customer/payments-team
  system: customer/payments
  definition:
    $text: https://github.com/stanleyhor/payments/blob/master/api-docs.yaml
  consumesApi:
   - afterpay-checkouts-api

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: afterpay-token-api
  title: AfterPay Token API
  namespace: customer
  description: "The Payments Auth Service handles payments authorizations and getting\
    \ auth token for multiple gateways, like AfterPay, ApplePay and PayPal (Braintree/Adyen)"
  annotations:
    backstage.io/kubernetes-namespace: payments-auth-service
  links:
    - https://developers.afterpay.com/docs/api/reference/checkouts/operations/create-a-v-2-checkout
spec:
  type: service
  lifecycle: production
  owner: group:customer/payments-team
  system: customer/payments
