apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: afterpay-team
  namespace: customer
  description: AfterPay team which handles AfterPay transactions.
spec:
  type: team
  profile:
    displayName: AfterPay Team
  parent: group:customer/services-team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: afterpay
  title: AfterPay
  namespace: customer
  description: "AfterPay Company"
  tags:
   - after-pay
spec:
  owner: group:customer/afterpay-team
  domain: customer/services

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: afterpay-api-service
  title: AfterPay API Service
  namespace: customer
  description: AfterPay API Service
spec:
  type: service
  lifecycle: production
  owner: group:customer/afterpay-team
  system: customer/afterpay
  providesApis:
   - afterpay-api

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: afterpay-api
  title: AfterPay API
  namespace: customer
  description: AfterPay API
spec:
  type: openapi
  lifecycle: production
  owner: group:customer/afterpay-team
  system: customer/afterpay
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: AfterPal APIs
      license:
        name: MIT
    servers:
      - url: https://api.us-sandbox.afterpay.com/v2
    paths:
      /checkouts:
        post:
          summary: Create token
          operationId: createToken
          tags:
            - token
          responses:
            '201':
              description: Null response
      /payments/auth:
        post:
          summary: Auth payment
          operationId: authPayment
          tags:
            - auth
          responses:
            '201':
              description: Null response
      /payments/token:
        post:
          summary: Reverse Auth payment
          operationId: reverseAuthPayment
          tags:
            - auth
          responses:
            '201':
              description: Null response
      /reversal:
        post:
          summary: Reverse Auth payment
          operationId: reverseAuthPayment
          tags:
            - auth
          responses:
            '201':
              description: Null response
