server:
  port: 8080
  max-http-request-header-size: 64KB
  compression:
    enabled: true
    min-response-size: 2KB
  tomcat:
    accept-count: 200
    max-connections: -1
    keep-alive-timeout: -1
    max-keep-alive-requests: -1
    threads:
      min-spare: 50
      max: 200
management:
  endpoint:
    health:
      show-details: always
    loggers:
      enabled: true
    env:
      post:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    circuitbreakers:
      enabled: true
  newrelic:
    metrics:
      export:
        enabled: false
logging:
  group:
    aeo: com.ecomm.payments
  level:
    aeo: INFO
aeo-logging:
  exclude-routes:
   - /actuator
---
spring:
  application:
    name: payments-auth-service
  main:
    allow-bean-definition-overriding: true
    keep-alive: "${spring.threads.virtual.enabled}"
  threads:
    virtual:
      enabled: "${VIRTUAL_THREADS_ENABLED:true}"
  jpa:
    database: postgresql
    open-in-view: true
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      '[hibernate.connection.provider_disables_autocommit]': false
      '[hibernate.jdbc.lob.non_contextual_creation]': true
      '[hibernate.dialect]': org.hibernate.dialect.PostgreSQLDialect
      '[jakarta.persistence.sharedCache.mode]': UNSPECIFIED
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-local.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/payments
    username: local
    password: root
    hikari:
      auto-commit: true
      register-mbeans: true
      max-lifetime: 600000
      idle-timeout: 300000
      connection-timeout: 20000
      leak-detection-threshold: 4000
    tomcat:
      jmx-enabled: true
  sql:
    init:
      platform: postgresql
      mode: never
  cloud:
    gcp:
      sql:
        enabled: false
      core:
        enabled: false
      pubsub:
        enabled: false
        emulator-host: 127.0.0.1:7100
        project-id: local-fake-project-id
      secretmanager:
        enabled: false
  autoconfigure:
    exclude:
     - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
---
input:
  connectTimeoutMillis: 30000
  readTimeoutMillis: 30000
  apiKey: "AQEyhmfuXNWTK0Qc+iSRn2EqrueaRq5MCp9Pd3BCwHG/imNZjQV72QP+9Zzod9mDy9yaqMUQwV1bDb7kfNy1WIxIIkxgBw==-iPxeBhz1TOWIlD/znQ9+aJ1Ocj8AaDPgKFEwRgjNpu0=-&Rb7Q;}6b,:33Lhz"
  paymentsAuthURL: https://checkout-test.adyen.com/checkout/v64
  paymentsAuthV2URL: https://checkout-test.adyen.com/v71
  paymentsDetailsEndPoint: /payments/details
  defaultOxxoShopperLocale: en_US
  useMock: false
  authSuccessResultCodes: "Authorised, Pending, Received, PresentToShopper"
  sleepTimeoutMillis: 1000
  skipAddress2ForAuth:
    "02953": "creditcard, applepay"
    "01790": creditcard
    "02954": creditcard
  merchantAccounts:
    "09021": AE_MX_Ecom
    "02953": AE_US_Ecom
    "01790": AE_CA_Ecom
    "02954": AE_INTL_Ecom
  resultCodeMap:
    Authorised: AUTHORIZED
    Refused: AUTHORIZE_REFUSED
    Error: ERROR
    RedirectShopper: REDIRECT_SHOPPER
    Pending: PENDING
    Received: RECEIVED
    Cancelled: CANCELLED
    PresentToShopper: VOUCHER
  paymentMethodType:
    creditcard: scheme
    giftcard: svs
    paypal: paypal
    oxxo: oxxo
    applepay: applepay
  channelType:
    WEB: Web
    MOBILE_WEB: Web
    IOS_APP: iOS
    ANDROID_APP: Android
  creditCardType:
    visa: visa
    mc: masterCard
    amex: americanExpress
    discover: discover
    jcb: jcb
    cup: cup
    diners: dinersClub
    synchrony_cbcc: aevisa
    synchrony_plcc: aecreditcard
    visa_applepay: visa
    discover_applepay: discover
    mc_applepay: masterCard
    amex_applepay: americanExpress
    jcb_applepay: jcb
    synchrony_cbcc_applepay: aevisa
    synchrony_plcc_applepay: aecreditcard
    interac_applepay: interac
  dbAllowedResultCodes: "AUTHORIZED, PENDING, REDIRECT_SHOPPER, VOUCHER, AUTH_PENDING,\
    \ SETTLED"
  allowedReauthCapturePayments: "paypal,applePay,creditCard,giftCard"
  allowedPaymentsForAuthTokenValidation: CREDITCARD
  emailsToBypassAuthCall: "aeprodcc@ae.com,aeprodcc_visa@ae.com,aeprodcc_mastercard@ae.com,aeprodcc_discover@ae.com,aeprodcc_amex@ae.com"
  afterpayServiceURL: https://api.us-sandbox.afterpay.com/v2
  afterpayTokenEndPoint: /checkouts
  afterpayAuthEndPoint: /payments/auth
  afterpayReverseAuthEndPoint: '/payments/token:'
  afterpayReverseAuthURI: /reversal
  afterpayConnectTimeoutMillis: 15000
  afterpayReadTimeoutMillis: 15000
  afterpayResultCodeMap:
    AUTH_APPROVED: AUTHORIZED
    AUTH_DECLINED: DECLINED
  braintreeServiceURL: https://payments.sandbox.braintree-api.com/graphql
  braintreeAuth: Basic dDZrYnFnNXNibmYyeXNmMjo3OGIyZWE1ZTA1ZWNhYTUwMWRlZDk0M2FhODJlMTk2ZA==
  braintreeVersion: 2024-02-01
  braintreeConnectTimeoutMillis: 30000
  braintreeReadTimeoutMillis: 30000
  braintreeSiteIdMerchantIdMap:
    AEO_US: americaneagle
    AEO_CA: americaneagleCA
    AEO_MX: americaneagleMX
  braintreeResultCodeMap:
    AUTHORIZED: AUTHORIZED
    GATEWAY_REJECTED: AUTHORIZE_REFUSED
    FAILED: AUTHORIZE_REFUSED
    PROCESSOR_DECLINED: AUTHORIZE_REFUSED
  afterpaySiteIdAuthMap:
    AEO_US: Basic MTAwMTAwMzc3OjkxMmFiYTEzMTJlYTlmMmNmMDBmNTM5YzJhYjI5YWFmZjBjM2IzNjU0MDIxOTFlZjQ1OGRkYjNmNDI4MWQ0NzNjY2Y5OWE5MDBlOWJlNWEwYTdlN2U5MzZiNTIwOTI1MDIwZGY1YmJkYzIzN2RlOTlkZDQzYjViMmJjNzdlZTgw
    AEO_CA: Basic MTAwMTAxMDM5OmFmYjU1ZTE5YjlkZjRlZDg4NzcxYjQ1NDkwMzE2N2Y0ZWQ1YTMwMGE1NDhhYjk2MmZiOGJlOTgyYTRmZDFlN2JhNjJmNTA1OTAyZTI3ZjM2NmRlNDJhZWQ5MDc0ZDU3ZjkxMDU1Njc1ZTYwNGJkODI3OGI0YTFkNzg4ZGJjMzM3
  sendPaypalPayeeEmail: true
  paypalPayeeEmailMap:
    AEO_US: american_eagle_biz@gmail.com
    AEO_CA: american_eagle_canada_biz@gmail.com
  synchronyCreditCards: "synchrony_plcc, synchrony_cbcc, synchrony_cbcc_applepay,\
    \ synchrony_plcc_applepay"
  saleTransactionPaymentMethods: interac_applepay
---
aeo-gcp-pubsub:
  publishers:
   -
    auto-configure: true
    bean-name: intlPaymentAuthPublisher
    project-id: local-fake-project-id
    topic-name: payments-auth-status-update-topic-sit
    batch-settings:
      frequency-ms: 1000
      batch-size: 5
  subscribers:
   -
    auto-configure: true
    auto-start: true
    bean-name: intlPaymentAuthSubscriber
    message-receiver-name: intlPaymentAuthReceiver
    project-id: local-fake-project-id
    subscription-name: payments-auth-status-update-sub-sit
    topic-name: payments-auth-status-update-topic-sit
    thread-count: 10
---
resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        allow-health-indicator-to-fail: false
        sliding-window-size: 10
        automatic-transition-from-open-to-half-open-enabled: true
        permitted-number-of-calls-in-half-open-state: 2
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 1m
        failure-rate-threshold: 50
        slow-call-duration-threshold: 12s
        slow-call-rate-threshold: 70
        event-consumer-buffer-size: 10
        sliding-window-type: COUNT_BASED
    instances:
      authorizationEndPoint:
        base-config: default
        ignore-exceptions:
         - org.springframework.web.client.RestClientResponseException
         - com.ecomm.payments.exception.AdyenClientException
      authorizationDetailEndPoint:
        base-config: default
        ignore-exceptions:
         - org.springframework.web.client.RestClientResponseException
         - com.ecomm.payments.exception.ClientException
         - com.ecomm.payments.exception.AuthorizationFailedException
      checkoutAfterpayService:
        base-config: default
        slow-call-duration-threshold: 7s
        ignore-exceptions:
         - org.springframework.web.client.RestClientResponseException
         - com.ecomm.payments.exception.ClientException
      authorizeAfterpayService:
        base-config: default
        slow-call-duration-threshold: 7s
        ignore-exceptions:
         - org.springframework.web.client.RestClientResponseException
         - com.ecomm.payments.exception.ClientException
         - com.ecomm.payments.exception.AuthorizationFailedException
      reverseAuthAfterpayService:
        base-config: default
        ignore-exceptions:
         - org.springframework.web.client.RestClientResponseException
         - com.ecomm.payments.exception.ClientException
      bTAuthCallService:
        base-config: default
      bTPaypalAuthCallService:
        base-config: default
      bTCreateClientTokenCallService:
        base-config: default
      adyenV2AuthCallService:
        base-config: default
        ignore-exceptions:
         - org.springframework.web.client.RestClientResponseException
         - com.ecomm.payments.exception.AdyenClientException
      adyenV2AuthDetailsService:
        base-config: default
        ignore-exceptions:
         - org.springframework.web.client.RestClientResponseException
         - com.ecomm.payments.exception.ClientException
         - com.ecomm.payments.exception.AuthorizationFailedException
springdoc:
  swagger-ui:
    path: /swagger-ui
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  packages-to-scan:
   - com.ecomm.payments.rest
   - com.aeo.gcp.pubsub.emulator
rsakey:
  public: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAreg6aHAV+5T8P9Mtm8/tJufeoT40nfU8UvSQ3NYWeyJfcgEtcRKnGqQy9sbs5YkGX4F5OAcrSP1JIvMeFEJRvsSa3EEDc8/f1qccUTgZA/cIT91MzSJgXpPojr2JHFnguUpjNtUf5d0sEXtSTW5KfdAQ5w7Kdq+1bcVRMovdiDelq4dMfWpmWva+eMaOi7fFWV19ZbhI8sUYu6zO8R02uyIlZhV4tjCzdeK5qsQ1rlSoPCgWfFlAXTc5ZjOrRLj9xpkpp7QQnQgU7JIE+C0McWxOzvj1k99EajS/bCevOdZyKju/SuKT9c8ZNPLPWsryCoVWpUepMg9CrJJYpN2XqQIDAQAB
basicAuthKeys:
 - MmIyMzdiZDAtYzZmYy00OGE0LWEzNjgtNmFjNDY1MmI2ZjU3OjExNGVmZWEyLWU0MzAtNGY0NS1iYzcwLTYwOTZkNmViYjc3NQ==
 - cGF5bWVudHMtaW50ZXJuYWwtZGV2OjA2N0NFMkQ1LTQxMzYtNDQ3Qy1COEU2LTZENDdCRDVDNTQwMg==
---
spring:
  boot:
    admin:
      client:
        enabled: false
